version: "3"

services:
  postgres:
    image: ekkus93/councilmatic-docker:latest
    container_name: councilmatic_scraper
    environment:
      - POSTGRES_PASSWORD=str0ng*p4ssw0rd
      - PGDATA=/var/lib/postgresql/data
    volumes:
      ### Sample
      #- <<local_db_data_dir>>:/var/lib/postgresql/data
      #- <<local_councilmatic-scraper_git_repo_dir>>:/home/postgres/work            
      ### Phil
      - /Users/phillipcchin/work/councilmatic/councilmatic-scraper-data:/var/lib/postgresql/data
      - /Users/phillipcchin/work/councilmatic/councilmatic-scraper:/home/postgres/work
      ### Howard
      #- /Users/matis/Dropbox/OpenOakland/councilmatic-scraper-data:/var/lib/postgresql/data
      #- /Users/matis/Dropbox/OpenOakland/councilmatic-scraper:/home/postgres/work      
    ports:
      - 7432:5432
      - 8888:8888
