version: "3"

services:
  scraper:
    image: ekkus93/councilmatic-docker:latest
    container_name: councilmatic_scraper
    environment:
      - POSTGRES_PASSWORD=str0ng*p4ssw0rd
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ../councilmatic-scraper-data:/var/lib/postgresql/data
      - ../councilmatic-scraper:/home/postgres/work
    ports:
      - 7432:5432
      - 8888:8888
