version: "3"

services:
  postgres:
    image: ekkus93/councilmatic-docker:latest
    container_name: councilmatic_postgres
    environment:
      - POSTGRES_PASSWORD=str0ng*p4ssw0rd
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - <<local_db_data_dir>>:/var/lib/postgresql/data
      - <<local_councilmatic-scraper_git_repo_dir>>:/home/postgres/work      
    ports:
      - 5432:5432
      - 8888:8888
  solr:
    image: solr
    container_name: councilmatic_solr
    ports:
     - 8983:8983
    volumes:
      - <<local_solr_data_dir>>:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
